### ISSUE TITLE
topology exception

### ISSUE THREAD

**Issue by knaaptime** [cenpy-devs/cenpy#95]
I'm working on the [data downloader](https://github.com/knaaptime/geosnap/blob/datasets/geosnap/util/cenpy_fetch.py) for geosnap that loops over each state and grabs the necessary variables. I need to do some more specific investigation, but California, New York and New Jersey fail for 2014 and 2015 with

```
TopologyException: Input geom 0 is invalid: Ring Self-intersection at or near point -8339755.5800000001 4964363.7000000002 at -8339755.5800000001 4964363.7000000002
```

the exact point is the same in each instance, and seems to be somewhere in jersey (40°40'26.123, -74°55'2.277")? I know we have some [handling](https://github.com/cenpy-devs/cenpy/blob/master/cenpy/geoparser.py) for this sort of thing, but not sure exactly how to address

**Comment by BryceStevenWilley** [comment]
I'm running into a similar issue with a very specific query: 
```

**Comment by BryceStevenWilley** [comment]
I'm running into a similar issue on a specific query: 
```
>>> deci = cenpy.products.Decennial2010()
>>> deci.from_county('Colombus, NC')
TopologyException: Input geom 0 is invalid: Ring Self-intersection at or near point -8721308.0299999993 4078462.2999999998 at -8721308.0299999993 4078462.2999999998
```
Which is Longitude: -78.344843; Latitude: 34.36903. Looking around in https://tigerweb.geo.census.gov/tigerweb/ shows that this is correct: and there's a ring there: 
![Screenshot from 2020-07-08 00-38-57](https://user-images.githubusercontent.com/6252212/86876803-7c946380-c0b3-11ea-8a2a-10972eaf9f87.png)

This same ring isn't present in the ACS from more recent years, as it seems like the issue got fixed. 
![Screenshot from 2020-07-08 00-39-10](https://user-images.githubusercontent.com/6252212/86876836-8ddd7000-c0b3-11ea-9c11-88ac003e5020.png)

However, this really minor issue is preventing me from getting any data from the 2010 census that's associated with the county. Is the best possible course of action to drop down to the Tiger and Census API's manually and combine the updated county shape from a more recent year to the census data of 2010?

**Comment by ljwolf** [comment]
Odd. Strict topology checking is off by default, so that error should be shown, but your data should still come through fine. 

Can you copy the full traceback too? I will try to reproduce this week.

**Comment by BryceStevenWilley** [comment]
For sure. I'm working on the pip package.

```
>>> import cenpy
>>> cenpy.__version__
'1.0.0post2'
>>> deci = cenpy.products.Decennial2010()
>>> x = deci.from_county('Colombus, NC')
/home/brycew/.local/lib/python3.6/site-packages/cenpy/geoparser.py:214: UserWarning: Shape is invalid: 
Ring Self-intersection[-8721308.03 4078462.3]
  tell_user('Shape is invalid: \n{}'.format(vexplain))
TopologyException: Input geom 0 is invalid: Ring Self-intersection at or near point -8721308.0299999993 4078462.2999999998 at -8721308.0299999993 4078462.2999999998
Traceback (most recent call last):
  File "/home/brycew/.local/lib/python3.6/site-packages/cenpy/geoparser.py", line 59, in convert_geometries
    [g.__dict__[e['type']](e) for e in df.geometry])
  File "/home/brycew/.local/lib/python3.6/site-packages/cenpy/geoparser.py", line 59, in <listcomp>
    [g.__dict__[e['type']](e) for e in df.geometry])
  File "/home/brycew/.local/lib/python3.6/site-packages/shapely/geometry/multipolygon.py", line 62, in __init__
    self._geom, self._ndim = geos_multipolygon_from_polygons(polygons)
  File "/home/brycew/.local/lib/python3.6/site-packages/shapely/geometry/multipolygon.py", line 185, in geos_multipolygon_from_polygons
    assert N == 2 or N == 3
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/brycew/.local/lib/python3.6/site-packages/cenpy/products.py", line 490, in from_county
    'Counties', **kwargs)
  File "/home/brycew/.local/lib/python3.6/site-packages/cenpy/products.py", line 437, in _from_name
    geometry_precision=geometry_precision)
  File "/home/brycew/.local/lib/python3.6/site-packages/cenpy/products.py", line 310, in _from_name
    cache_name=cache_name)
  File "/home/brycew/.local/lib/python3.6/site-packages/cenpy/products.py", line 293, in _environment_from_layer
    geometryPrecision=geometry_precision)
  File "/home/brycew/.local/lib/python3.6/site-packages/cenpy/tiger.py", line 205, in query
    outdf = gpsr.convert_geometries(df, strict=strict)
  File "/home/brycew/.local/lib/python3.6/site-packages/cenpy/geoparser.py", line 63, in convert_geometries
    for e in df.geometry])
  File "/home/brycew/.local/lib/python3.6/site-packages/cenpy/geoparser.py", line 63, in <listcomp>
    for e in df.geometry])
  File "/home/brycew/.local/lib/python3.6/site-packages/cenpy/geoparser.py", line 92, in parse_polygon
    out = fix_rings(out, strict=strict)
  File "/home/brycew/.local/lib/python3.6/site-packages/cenpy/geoparser.py", line 229, in fix_rings
    polygons[i] = exterior.difference(cascaded_union(owned_interiors))
  File "/home/brycew/.local/lib/python3.6/site-packages/shapely/geometry/base.py", line 645, in difference
    return geom_factory(self.impl['difference'](self, other))
  File "/home/brycew/.local/lib/python3.6/site-packages/shapely/topology.py", line 70, in __call__
    self._check_topology(err, this, other)
  File "/home/brycew/.local/lib/python3.6/site-packages/shapely/topology.py", line 38, in _check_topology
    self.fn.__name__, repr(geom)))
shapely.errors.TopologicalError: The operation 'GEOSDifference_r' could not be performed. Likely cause is invalidity of the geometry <shapely.geometry.polygon.Polygon object at 0x7fb315dea2e8>
```

**Comment by ljwolf** [comment]
Ah, sorry, could I also trouble you for your version of shapely?

**Comment by ljwolf** [comment]
Just from your traceback, this clarifies that this exception is raised at the shapely level, not within cenpy, and occurs when trying to filter the geometries by the requested containing shape. I'll see what I can do. I may be able to force the polygons to validate before trying to compute the difference.

**Comment by BryceStevenWilley** [comment]
Shapely is version `1.7.0`!

And I see, that makes sense. Let me know if you need anything else!

**Comment by martinfleis** [comment]
Just ran into this. 

Apparently some geometries coming from census are invalid (for GEOS model, may be valid for ArcGIS) so we should try to fix topology before this line

```
polygons[i] = exterior.difference(cascaded_union(owned_interiors))
```

Maybe simple `buffer(0)` would do the trick?

**Comment by martinfleis** [comment]
I have replaced this whole function with `return multipolygon.buffer(0)` and my query was successful. As well as tests. If the point of `fix_rings` is to validate multipolygon, isn't it better just to use that instead of the current complex heuristics which does not fix all the issues?

https://github.com/cenpy-devs/cenpy/blob/fde2ad6c71d4a81aab6d8950d76c39b36b9d377c/cenpy/geoparser.py#L188

**Comment by dfolch** [comment]
Another example of this issue. This time with North Carolina PUMAs (PUMAs for all other states are fine).
``` python
cxn = cenpy.tiger.TigerConnection('PUMA_TAD_TAZ_UGA_ZCTA')
layer = '(ESRILayer) Public Use Microdata Areas'
index = [f.__repr__() for f in cxn.layers].index(layer)
az_pumas = cxn.layers[index].query(where = 'STATE = 37')
```
Output
``` python
/lib/python3.8/site-packages/cenpy/geoparser.py:226: UserWarning: Shape is invalid: 
Ring Self-intersection[-9131093.2197 4284180.0737]
  tell_user("Shape is invalid: \n{}".format(vexplain))
TopologyException: Input geom 0 is invalid: Ring Self-intersection at or near point -9131093.2196999993 4284180.0737000033 at -9131093.2196999993 4284180.0737000033
```
